[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    base-uri 'self';
    object-src 'none';
    img-src * data: blob:;
    font-src 'self' https://studio-static.sanity.io https://sanity-cdn.com https://core.sanity-cdn.com https://cdn.sanity.io data:;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https://sanity-cdn.com https://core.sanity-cdn.com https://modules.sanity-cdn.com https://cdn.sanity.io https://plasmic.app https://*.plasmic.app;
    style-src 'self' 'unsafe-inline';
    connect-src 'self'
      https://api.sanity.io
      https://*.sanity.io
      https://fo6n8ceo.api.sanity.io
      wss://*.sanity.io
      wss://fo6n8ceo.api.sanity.io
      https://sanity-cdn.com
      https://core.sanity-cdn.com
      https://modules.sanity-cdn.com
      https://plasmic.app
      https://*.plasmic.app
      https://hq.benextglobal.com
      https://futurohq.netlify.app;
    worker-src 'self' blob:;
    frame-src 'self';
    frame-ancestors 'self';
  """

# --- Favicon cache-busting (unchanged) ---
[[headers]]
  for = "/favicon.ico"
  [headers.values]
  Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/favicon-32x32.png"
  [headers.values]
  Cache-Control = "no-cache, must-revalidate"

# (Optional)
# [[headers]]
#   for = "/apple-touch-icon.png"
#   [headers.values]
#   Cache-Control = "no-cache, must-revalidate"

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
